#!/bin/bash

if [ -a $1 ]
then
    echo "File exists"
    exit 1
fi

mkdir $1 && cd $_

cat > package.json <<EOF
{
    "name": "${1##*/}",
    "version": "0.0.1",
    "scripts": {
        "build": "webpack",
        "watch": "webpack --watch",
        "start": "webpack serve --open"
    },
    "devDependencies": {}
}
EOF

npm install \
    react \
    react-dom \
    @babel/core \
    @babel/preset-env \
    @babel/preset-react \
    webpack \
    webpack-cli \
    webpack-dev-server \
    html-webpack-plugin \
    style-loader \
    css-loader \
    sass-loader \
    babel-loader \
    --save-dev

# cat > .babelrc.json <<EOF
# {
#     "presets": [ "@babel/preset-env", "@babel/preset-react" ]
# }
# EOF

cat > webpack.config.js <<EOF
const path = require("path")
const HtmlWebpackPlugin = require("html-webpack-plugin")

module.exports = {
    entry: "./src/index.js",
    mode: "development",
    devtool: 'inline-source-map',
    devServer: {
        contentBase: path.join(__dirname, 'dist'),
        hot: true
    },
    plugins: [
        new HtmlWebpackPlugin({
            title: "${1##*/}",
            template: path.resolve(__dirname, "src/index.html")
        }),
    ],
    module: {
        rules: [
            {
                test: /\.(js|jsx)/i,
                exclude: /node_modules/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        // The following line can be replaced by a .babelrc.json config file
                        presets: [ "@babel/preset-env", "@babel/preset-react" ]
                    }
                }
            }
        ]
    },
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: 'bundle.js'
    }
}
EOF

mkdir src

cat > src/index.js <<EOF
import React from "react"
import ReactDOM from "react-dom"

ReactDOM.render(<h1>Hello World!</h1>, document.getElementById("root"))
EOF

cat > src/index.html <<EOF
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <div id="root"></div>
</body>
</html>
EOF

npm run-script build
